<?php
require $_SERVER['DOCUMENT_ROOT'] . '/bitrix/header.php';
$APPLICATION->SetTitle('Поиск по товарам');

$APPLICATION->IncludeComponent(
    'brakes:catalog.search',
    '',
    [
        'IBLOCK_TYPE' => '1c_catalog',
        'IBLOCK_ID' => '1',
        'FILTER_NAME' => 'catalogSearchFilter',
        'QUERY_VARIABLE' => 'q',
        'CATALOG_TEMPLATE' => 'search',
        'SEARCH_LIMIT' => '500',
        'CHECK_DATES' => 'Y',
        'ERROR_ON_EMPTY_STEM' => 'N',
        'NO_WORD_LOGIC' => 'Y',
        'ELEMENT_SORT_FIELD' => 'sort',
        'ELEMENT_SORT_ORDER' => 'asc',
        'ELEMENT_SORT_FIELD2' => 'id',
        'ELEMENT_SORT_ORDER2' => 'desc',
        'SECTION_URL' => '/catalog/#SECTION_CODE_PATH#/',
        'DETAIL_URL' => '/catalog/#SECTION_CODE_PATH#/#ELEMENT_CODE#/',
        'BASKET_URL' => '/personal/cart/',
        'ACTION_VARIABLE' => 'action',
        'PRODUCT_ID_VARIABLE' => 'id',
        'PRODUCT_QUANTITY_VARIABLE' => 'quantity',
        'PRODUCT_PROPS_VARIABLE' => 'prop',
        'SECTION_ID_VARIABLE' => 'SECTION_ID',
        'DISPLAY_COMPARE' => 'N',
        'PAGE_ELEMENT_COUNT' => '20',
        'LINE_ELEMENT_COUNT' => '3',
        'PROPERTY_CODE' => [],
        'OFFERS_FIELD_CODE' => [
            'PREVIEW_PICTURE',
            'DETAIL_PICTURE',
        ],
        'OFFERS_PROPERTY_CODE' => [],
        'OFFERS_SORT_FIELD' => 'sort',
        'OFFERS_SORT_ORDER' => 'asc',
        'OFFERS_SORT_FIELD2' => 'id',
        'OFFERS_SORT_ORDER2' => 'desc',
        'OFFERS_LIMIT' => '5',
        'PRICE_CODE' => [
            'РРЦ',
        ],
        'USE_PRICE_COUNT' => 'N',
        'SHOW_PRICE_COUNT' => '1',
        'PRICE_VAT_INCLUDE' => 'Y',
        'USE_PRODUCT_QUANTITY' => 'Y',
        'CACHE_TYPE' => 'A',
        'CACHE_TIME' => '36000000',
        'CACHE_FILTER' => 'Y',
        'CACHE_GROUPS' => 'Y',
        'DISPLAY_TOP_PAGER' => 'N',
        'DISPLAY_BOTTOM_PAGER' => 'Y',
        'PAGER_TITLE' => 'Товары',
        'PAGER_SHOW_ALWAYS' => 'N',
        'PAGER_TEMPLATE' => '',
        'PAGER_DESC_NUMBERING' => 'N',
        'PAGER_DESC_NUMBERING_CACHE_TIME' => '36000',
        'PAGER_SHOW_ALL' => 'N',
        'HIDE_NOT_AVAILABLE' => 'N',
        'CONVERT_CURRENCY' => 'Y',
        'CURRENCY_ID' => 'RUB',
        'OFFERS_CART_PROPERTIES' => [],
        'ADD_SECTIONS_CHAIN' => 'N',
        'SET_TITLE' => 'N',
        'SET_BROWSER_TITLE' => 'N',
        'SET_META_KEYWORDS' => 'N',
        'SET_META_DESCRIPTION' => 'N',
        'SET_LAST_MODIFIED' => 'N',
        'INCLUDE_SUBSECTIONS' => 'Y',
        'SHOW_ALL_WO_SECTION' => 'Y',
        'MESSAGE_404' => '',
        'SET_STATUS_404' => 'N',
        'SHOW_404' => 'N',
        'SEF_MODE' => 'N',
    ],
    false
);

require $_SERVER['DOCUMENT_ROOT'] . '/bitrix/footer.php';
